services:
  - type: web
    name: kk-bank-backend
    runtime: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: MYSQL_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
